---
title: "Research Interests"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My research centers on understanding health and resilience as emergent properties of complex physiological systems. I’m especially interested in:

**Physiological Complexity**: How patterns in time series data (e.g., heart rate, respiration, blood pressure, temperature, galvanic skin response, activity, sleep) reflect the adaptability and stability of the human body.

**Intrinsic Health**: Investigating health as a systems-level state, rather than as the absence of specific diseases.

**Quantitative Methods**: Applying tools from complexity science (e.g., entropy, fractality, transfer entropy), statistical modeling, time series representation learning, and deep learning to characterize health dynamics.

**Self-Rated Health**: Exploring interesting patterns in the deceptively simple yet powerful survey question: In general, would you say your health is... [Excellent/Very Good/Good/Fair/Poor].

**Environmental Stressors**: Examining how exposures like heat waves and humidity influence physiological resilience and population health.

**Multiscale Integration**: Bridging wearable sensor data, clinical Holter monitors, and population health surveys to compare health signals across  scales.







[.](https://docs.google.com/presentation/d/1aVn9p4m8hOSTo88XoyupjzMOdtgCQPAlmr_LmpRvZng/edit?usp=sharing) [.](https://docs.google.com/presentation/d/1bm7gZeY0GhB_ZhD-Ui5tCrzBcc92i2Tz52xHnlbfopI/edit?usp=sharing)
